{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"customer_dim\",\"fact_table\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.121.644.0 (23.09)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "67711521-9431-4ed5-8978-d14b8451811b",
        "fromColumn": "coustomer_key",
        "fromTable": "fact_table",
        "toColumn": "coustomer_key",
        "toTable": "customer_dim"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "customer_dim",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "coustomer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff2340a2-8ccf-47a0-820d-400d850ddae8",
            "sourceColumn": "coustomer_key",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd8bec9e-d404-4fd3-9e8a-6b8df10bd58c",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "contact_no",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e4e8e6ea-b4be-4fd1-8fb3-fc776efa2e61",
            "sourceColumn": "contact_no",
            "summarizeBy": "none"
          },
          {
            "name": "nid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "87b4d9dc-e06e-4309-898c-7e894a45b8d1",
            "sourceColumn": "nid",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7e6112aa-c30e-4537-814f-182eaf1bfc85",
        "partitions": [
          {
            "name": "customer_dim",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\bnavi\\Desktop\\Projects\\E-Commerce\\customer_dim.csv\"),[Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"coustomer_key\", type text}, {\"name\", type text}, {\"contact_no\", Int64.Type}, {\"nid\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_7e214577-55a2-4e19-91d8-2788d1ad4ffb",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "14aebd8b-d741-42a0-b079-5dd599823d34",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5e3071e0-88c2-45c2-8d06-3ec355b152ed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ecf89165-4c23-4fb2-bf7f-921e5a35ace9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "eded809c-b16b-4265-a9d4-f20637173d80",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "236b1f5d-9136-40e8-886b-4e21d1404cf6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "96503668-56ae-406a-9e68-6bba6e709d42",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fc7bbfe1-199e-41a3-883f-c3c96af015f0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0ffb151f-b481-4d6c-8755-c12c036e7dd9",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a642e7c1-4d01-4752-9f4b-63f4b465b36a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "06a06cdd-7ee1-4c71-9193-9728faa236e2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "cd8ac20e-e355-4825-be19-059ad2a1cbc8",
                "ordinal": 3
              }
            ],
            "lineageTag": "21c0dcf9-5d3b-4f1b-8784-9d00994d842a"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "4a318b8e-5f42-42ee-ba76-f24ef7cd2469",
        "partitions": [
          {
            "name": "DateTableTemplate_7e214577-55a2-4e19-91d8-2788d1ad4ffb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "fact_table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "payment_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "247d3d35-3771-4d4d-b01e-2a6b7feb7325",
            "sourceColumn": "payment_key",
            "summarizeBy": "none"
          },
          {
            "name": "coustomer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93b87273-7a8c-4b4c-ac3d-8d92ebf5ded8",
            "sourceColumn": "coustomer_key",
            "summarizeBy": "none"
          },
          {
            "name": "time_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "335b63b3-225a-4bdc-82b0-c4ac869a05a3",
            "sourceColumn": "time_key",
            "summarizeBy": "none"
          },
          {
            "name": "item_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4789b96-66c2-4175-b017-3d035fcf98a8",
            "sourceColumn": "item_key",
            "summarizeBy": "none"
          },
          {
            "name": "store_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0a7fce3-d611-4914-a396-9a299a1f6d31",
            "sourceColumn": "store_key",
            "summarizeBy": "none"
          },
          {
            "name": "quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f5dbbb6-8c97-4079-b6c6-2ddd3299a804",
            "sourceColumn": "quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cea8c97a-11e4-47c9-99ba-c410ee7c958f",
            "sourceColumn": "unit",
            "summarizeBy": "none"
          },
          {
            "name": "unit_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f3be5a59-316b-4770-8c78-ec6b499a2a15",
            "sourceColumn": "unit_price",
            "summarizeBy": "sum"
          },
          {
            "name": "total_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1179c1e5-55c4-41fa-90e9-afe7c9c17551",
            "sourceColumn": "total_price",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c78f85c0-7bc2-4afe-9bab-6fab8e97df75",
        "partitions": [
          {
            "name": "fact_table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\bnavi\\Desktop\\Projects\\E-Commerce\\fact_table.csv\"),[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"payment_key\", type text}, {\"coustomer_key\", type text}, {\"time_key\", type text}, {\"item_key\", type text}, {\"store_key\", type text}, {\"quantity\", Int64.Type}, {\"unit\", type text}, {\"unit_price\", type number}, {\"total_price\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}